version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      gomod:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /pkg/infra
    schedule:
      interval: monthly
    groups:
      docker:
        patterns: [ "*" ]
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: monthly
    groups:
      docker:
        patterns: [ "*" ]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: main
    groups:
      actions:
        patterns: [ "*" ]
